// Generated by gencpp from file set_pose/SetPoseResult.msg
// DO NOT EDIT!


#ifndef SET_POSE_MESSAGE_SETPOSERESULT_H
#define SET_POSE_MESSAGE_SETPOSERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace set_pose
{
template <class ContainerAllocator>
struct SetPoseResult_
{
  typedef SetPoseResult_<ContainerAllocator> Type;

  SetPoseResult_()
    : succeeded(false)  {
    }
  SetPoseResult_(const ContainerAllocator& _alloc)
    : succeeded(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeeded_type;
  _succeeded_type succeeded;





  typedef boost::shared_ptr< ::set_pose::SetPoseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::set_pose::SetPoseResult_<ContainerAllocator> const> ConstPtr;

}; // struct SetPoseResult_

typedef ::set_pose::SetPoseResult_<std::allocator<void> > SetPoseResult;

typedef boost::shared_ptr< ::set_pose::SetPoseResult > SetPoseResultPtr;
typedef boost::shared_ptr< ::set_pose::SetPoseResult const> SetPoseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::set_pose::SetPoseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::set_pose::SetPoseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace set_pose

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'set_pose': ['/home/ubuntu/bill_ros/bill_ws/devel/share/set_pose/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::set_pose::SetPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::set_pose::SetPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::set_pose::SetPoseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::set_pose::SetPoseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::set_pose::SetPoseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::set_pose::SetPoseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::set_pose::SetPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e696a0d10686913abb262e0b4cbbcf";
  }

  static const char* value(const ::set_pose::SetPoseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e696a0d1068691ULL;
  static const uint64_t static_value2 = 0x3abb262e0b4cbbcfULL;
};

template<class ContainerAllocator>
struct DataType< ::set_pose::SetPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "set_pose/SetPoseResult";
  }

  static const char* value(const ::set_pose::SetPoseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::set_pose::SetPoseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
bool succeeded\n\
";
  }

  static const char* value(const ::set_pose::SetPoseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::set_pose::SetPoseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPoseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::set_pose::SetPoseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::set_pose::SetPoseResult_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SET_POSE_MESSAGE_SETPOSERESULT_H
