// Auto-generated. Do not edit!

// (in-package poi_scan.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PoiScanResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.tasks_completed = null;
    }
    else {
      if (initObj.hasOwnProperty('tasks_completed')) {
        this.tasks_completed = initObj.tasks_completed
      }
      else {
        this.tasks_completed = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PoiScanResult
    // Serialize message field [tasks_completed]
    bufferOffset = _serializer.uint32(obj.tasks_completed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PoiScanResult
    let len;
    let data = new PoiScanResult(null);
    // Deserialize message field [tasks_completed]
    data.tasks_completed = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'poi_scan/PoiScanResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5b91649fc9318ff816a5a104781a31a1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 tasks_completed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PoiScanResult(null);
    if (msg.tasks_completed !== undefined) {
      resolved.tasks_completed = msg.tasks_completed;
    }
    else {
      resolved.tasks_completed = 0
    }

    return resolved;
    }
};

module.exports = PoiScanResult;
