// Generated by gencpp from file poi_scan/PoiScanFeedback.msg
// DO NOT EDIT!


#ifndef POI_SCAN_MESSAGE_POISCANFEEDBACK_H
#define POI_SCAN_MESSAGE_POISCANFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poi_scan
{
template <class ContainerAllocator>
struct PoiScanFeedback_
{
  typedef PoiScanFeedback_<ContainerAllocator> Type;

  PoiScanFeedback_()
    : percent_complete(0.0)  {
    }
  PoiScanFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::poi_scan::PoiScanFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_scan::PoiScanFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PoiScanFeedback_

typedef ::poi_scan::PoiScanFeedback_<std::allocator<void> > PoiScanFeedback;

typedef boost::shared_ptr< ::poi_scan::PoiScanFeedback > PoiScanFeedbackPtr;
typedef boost::shared_ptr< ::poi_scan::PoiScanFeedback const> PoiScanFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_scan::PoiScanFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'poi_scan': ['/home/ubuntu/bill_ros/bill_ws/devel/share/poi_scan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::poi_scan::PoiScanFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_scan/PoiScanFeedback";
  }

  static const char* value(const ::poi_scan::PoiScanFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 percent_complete\n\
\n\
";
  }

  static const char* value(const ::poi_scan::PoiScanFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoiScanFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_scan::PoiScanFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_scan::PoiScanFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_SCAN_MESSAGE_POISCANFEEDBACK_H
