// Generated by gencpp from file poi_scan/PoiScanResult.msg
// DO NOT EDIT!


#ifndef POI_SCAN_MESSAGE_POISCANRESULT_H
#define POI_SCAN_MESSAGE_POISCANRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poi_scan
{
template <class ContainerAllocator>
struct PoiScanResult_
{
  typedef PoiScanResult_<ContainerAllocator> Type;

  PoiScanResult_()
    : tasks_completed(0)  {
    }
  PoiScanResult_(const ContainerAllocator& _alloc)
    : tasks_completed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _tasks_completed_type;
  _tasks_completed_type tasks_completed;





  typedef boost::shared_ptr< ::poi_scan::PoiScanResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_scan::PoiScanResult_<ContainerAllocator> const> ConstPtr;

}; // struct PoiScanResult_

typedef ::poi_scan::PoiScanResult_<std::allocator<void> > PoiScanResult;

typedef boost::shared_ptr< ::poi_scan::PoiScanResult > PoiScanResultPtr;
typedef boost::shared_ptr< ::poi_scan::PoiScanResult const> PoiScanResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_scan::PoiScanResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_scan::PoiScanResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'poi_scan': ['/home/ubuntu/bill_ros/bill_ws/devel/share/poi_scan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_scan::PoiScanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b91649fc9318ff816a5a104781a31a1";
  }

  static const char* value(const ::poi_scan::PoiScanResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b91649fc9318ff8ULL;
  static const uint64_t static_value2 = 0x16a5a104781a31a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_scan::PoiScanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_scan/PoiScanResult";
  }

  static const char* value(const ::poi_scan::PoiScanResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_scan::PoiScanResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
uint32 tasks_completed\n\
";
  }

  static const char* value(const ::poi_scan::PoiScanResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_scan::PoiScanResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tasks_completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoiScanResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_scan::PoiScanResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_scan::PoiScanResult_<ContainerAllocator>& v)
  {
    s << indent << "tasks_completed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tasks_completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_SCAN_MESSAGE_POISCANRESULT_H
