// Generated by gencpp from file poi_scan/PoiScanAction.msg
// DO NOT EDIT!


#ifndef POI_SCAN_MESSAGE_POISCANACTION_H
#define POI_SCAN_MESSAGE_POISCANACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <poi_scan/PoiScanActionGoal.h>
#include <poi_scan/PoiScanActionResult.h>
#include <poi_scan/PoiScanActionFeedback.h>

namespace poi_scan
{
template <class ContainerAllocator>
struct PoiScanAction_
{
  typedef PoiScanAction_<ContainerAllocator> Type;

  PoiScanAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  PoiScanAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::poi_scan::PoiScanActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::poi_scan::PoiScanActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::poi_scan::PoiScanActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::poi_scan::PoiScanAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_scan::PoiScanAction_<ContainerAllocator> const> ConstPtr;

}; // struct PoiScanAction_

typedef ::poi_scan::PoiScanAction_<std::allocator<void> > PoiScanAction;

typedef boost::shared_ptr< ::poi_scan::PoiScanAction > PoiScanActionPtr;
typedef boost::shared_ptr< ::poi_scan::PoiScanAction const> PoiScanActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_scan::PoiScanAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_scan::PoiScanAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'poi_scan': ['/home/ubuntu/bill_ros/bill_ws/devel/share/poi_scan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_scan::PoiScanAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5880b8fb9905b98a27ef2a0443df64f5";
  }

  static const char* value(const ::poi_scan::PoiScanAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5880b8fb9905b98aULL;
  static const uint64_t static_value2 = 0x27ef2a0443df64f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_scan::PoiScanAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_scan/PoiScanAction";
  }

  static const char* value(const ::poi_scan::PoiScanAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_scan::PoiScanAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
PoiScanActionGoal action_goal\n\
PoiScanActionResult action_result\n\
PoiScanActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
PoiScanGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string[] topics              # list of topics to record\n\
string   bagfile_name_prefix # output bagfiles will begin with this prefix. Suffixes will be generated like \"_pos0.bag\"\n\
uint32   num_stops           # number of times to stop during one 360degree rotation\n\
float32  tune_rotation       # for example, value of 1.05 will overrotate 5% to compensate for natural underrrotation\n\
float32  duration            # number of seconds to pause at each stop\n\
bool     return_to_original  # set to true, if you want to return to original orientation when done\n\
string   upload_url          # after recording rosbag, automatically upload here\n\
bool     rm_after_upload     # if set to True, rosbag will be rm'd from turtlebot after successful upload\n\
string   upload_token        # authorization token for upload server\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
PoiScanResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
uint32 tasks_completed\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
PoiScanFeedback feedback\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define a feedback message\n\
float32 percent_complete\n\
\n\
";
  }

  static const char* value(const ::poi_scan::PoiScanAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_scan::PoiScanAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoiScanAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_scan::PoiScanAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_scan::PoiScanAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::poi_scan::PoiScanActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::poi_scan::PoiScanActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_SCAN_MESSAGE_POISCANACTION_H
