// Generated by gencpp from file poi_scan/PoiScanActionGoal.msg
// DO NOT EDIT!


#ifndef POI_SCAN_MESSAGE_POISCANACTIONGOAL_H
#define POI_SCAN_MESSAGE_POISCANACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <poi_scan/PoiScanGoal.h>

namespace poi_scan
{
template <class ContainerAllocator>
struct PoiScanActionGoal_
{
  typedef PoiScanActionGoal_<ContainerAllocator> Type;

  PoiScanActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  PoiScanActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::poi_scan::PoiScanGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PoiScanActionGoal_

typedef ::poi_scan::PoiScanActionGoal_<std::allocator<void> > PoiScanActionGoal;

typedef boost::shared_ptr< ::poi_scan::PoiScanActionGoal > PoiScanActionGoalPtr;
typedef boost::shared_ptr< ::poi_scan::PoiScanActionGoal const> PoiScanActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_scan::PoiScanActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_scan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'poi_scan': ['/home/ubuntu/bill_ros/bill_ws/devel/share/poi_scan/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5a9dd3384253ed894bbfc71658c36ae";
  }

  static const char* value(const ::poi_scan::PoiScanActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5a9dd3384253ed8ULL;
  static const uint64_t static_value2 = 0x94bbfc71658c36aeULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_scan/PoiScanActionGoal";
  }

  static const char* value(const ::poi_scan::PoiScanActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
PoiScanGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: poi_scan/PoiScanGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
string[] topics              # list of topics to record\n\
string   bagfile_name_prefix # output bagfiles will begin with this prefix. Suffixes will be generated like \"_pos0.bag\"\n\
uint32   num_stops           # number of times to stop during one 360degree rotation\n\
float32  tune_rotation       # for example, value of 1.05 will overrotate 5% to compensate for natural underrrotation\n\
float32  duration            # number of seconds to pause at each stop\n\
bool     return_to_original  # set to true, if you want to return to original orientation when done\n\
string   upload_url          # after recording rosbag, automatically upload here\n\
bool     rm_after_upload     # if set to True, rosbag will be rm'd from turtlebot after successful upload\n\
string   upload_token        # authorization token for upload server\n\
";
  }

  static const char* value(const ::poi_scan::PoiScanActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoiScanActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_scan::PoiScanActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_scan::PoiScanActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::poi_scan::PoiScanGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_SCAN_MESSAGE_POISCANACTIONGOAL_H
