// Generated by gencpp from file poi_name_locator/PoiNameLocatorResponse.msg
// DO NOT EDIT!


#ifndef POI_NAME_LOCATOR_MESSAGE_POINAMELOCATORRESPONSE_H
#define POI_NAME_LOCATOR_MESSAGE_POINAMELOCATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace poi_name_locator
{
template <class ContainerAllocator>
struct PoiNameLocatorResponse_
{
  typedef PoiNameLocatorResponse_<ContainerAllocator> Type;

  PoiNameLocatorResponse_()
    : position()  {
    }
  PoiNameLocatorResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoiNameLocatorResponse_

typedef ::poi_name_locator::PoiNameLocatorResponse_<std::allocator<void> > PoiNameLocatorResponse;

typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorResponse > PoiNameLocatorResponsePtr;
typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorResponse const> PoiNameLocatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_name_locator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7bb0ef028c744b081acdc57743b11d8";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7bb0ef028c744b0ULL;
  static const uint64_t static_value2 = 0x81acdc57743b11d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_name_locator/PoiNameLocatorResponse";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoiNameLocatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_name_locator::PoiNameLocatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_NAME_LOCATOR_MESSAGE_POINAMELOCATORRESPONSE_H
