// Generated by gencpp from file poi_name_locator/PoiNameLocator.msg
// DO NOT EDIT!


#ifndef POI_NAME_LOCATOR_MESSAGE_POINAMELOCATOR_H
#define POI_NAME_LOCATOR_MESSAGE_POINAMELOCATOR_H

#include <ros/service_traits.h>


#include <poi_name_locator/PoiNameLocatorRequest.h>
#include <poi_name_locator/PoiNameLocatorResponse.h>


namespace poi_name_locator
{

struct PoiNameLocator
{

typedef PoiNameLocatorRequest Request;
typedef PoiNameLocatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoiNameLocator
} // namespace poi_name_locator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::poi_name_locator::PoiNameLocator > {
  static const char* value()
  {
    return "91b7101264f88cf4becf629edfa6879e";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocator&) { return value(); }
};

template<>
struct DataType< ::poi_name_locator::PoiNameLocator > {
  static const char* value()
  {
    return "poi_name_locator/PoiNameLocator";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocator&) { return value(); }
};


// service_traits::MD5Sum< ::poi_name_locator::PoiNameLocatorRequest> should match 
// service_traits::MD5Sum< ::poi_name_locator::PoiNameLocator > 
template<>
struct MD5Sum< ::poi_name_locator::PoiNameLocatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::poi_name_locator::PoiNameLocator >::value();
  }
  static const char* value(const ::poi_name_locator::PoiNameLocatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_name_locator::PoiNameLocatorRequest> should match 
// service_traits::DataType< ::poi_name_locator::PoiNameLocator > 
template<>
struct DataType< ::poi_name_locator::PoiNameLocatorRequest>
{
  static const char* value()
  {
    return DataType< ::poi_name_locator::PoiNameLocator >::value();
  }
  static const char* value(const ::poi_name_locator::PoiNameLocatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::poi_name_locator::PoiNameLocatorResponse> should match 
// service_traits::MD5Sum< ::poi_name_locator::PoiNameLocator > 
template<>
struct MD5Sum< ::poi_name_locator::PoiNameLocatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::poi_name_locator::PoiNameLocator >::value();
  }
  static const char* value(const ::poi_name_locator::PoiNameLocatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::poi_name_locator::PoiNameLocatorResponse> should match 
// service_traits::DataType< ::poi_name_locator::PoiNameLocator > 
template<>
struct DataType< ::poi_name_locator::PoiNameLocatorResponse>
{
  static const char* value()
  {
    return DataType< ::poi_name_locator::PoiNameLocator >::value();
  }
  static const char* value(const ::poi_name_locator::PoiNameLocatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POI_NAME_LOCATOR_MESSAGE_POINAMELOCATOR_H
