// Generated by gencpp from file poi_name_locator/PoiNameLocatorRequest.msg
// DO NOT EDIT!


#ifndef POI_NAME_LOCATOR_MESSAGE_POINAMELOCATORREQUEST_H
#define POI_NAME_LOCATOR_MESSAGE_POINAMELOCATORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace poi_name_locator
{
template <class ContainerAllocator>
struct PoiNameLocatorRequest_
{
  typedef PoiNameLocatorRequest_<ContainerAllocator> Type;

  PoiNameLocatorRequest_()
    : poi_name()  {
    }
  PoiNameLocatorRequest_(const ContainerAllocator& _alloc)
    : poi_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _poi_name_type;
  _poi_name_type poi_name;





  typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PoiNameLocatorRequest_

typedef ::poi_name_locator::PoiNameLocatorRequest_<std::allocator<void> > PoiNameLocatorRequest;

typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorRequest > PoiNameLocatorRequestPtr;
typedef boost::shared_ptr< ::poi_name_locator::PoiNameLocatorRequest const> PoiNameLocatorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace poi_name_locator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf0217b1043bf59a315e33a82128608a";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf0217b1043bf59aULL;
  static const uint64_t static_value2 = 0x315e33a82128608aULL;
};

template<class ContainerAllocator>
struct DataType< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "poi_name_locator/PoiNameLocatorRequest";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string poi_name\n\
";
  }

  static const char* value(const ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poi_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoiNameLocatorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::poi_name_locator::PoiNameLocatorRequest_<ContainerAllocator>& v)
  {
    s << indent << "poi_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.poi_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POI_NAME_LOCATOR_MESSAGE_POINAMELOCATORREQUEST_H
