(cl:defpackage set_pose-msg
  (:use )
  (:export
   "<SETPOSEACTION>"
   "SETPOSEACTION"
   "<SETPOSEACTIONFEEDBACK>"
   "SETPOSEACTIONFEEDBACK"
   "<SETPOSEACTIONGOAL>"
   "SETPOSEACTIONGOAL"
   "<SETPOSEACTIONRESULT>"
   "SETPOSEACTIONRESULT"
   "<SETPOSEFEEDBACK>"
   "SETPOSEFEEDBACK"
   "<SETPOSEGOAL>"
   "SETPOSEGOAL"
   "<SETPOSERESULT>"
   "SETPOSERESULT"
  ))

