; Auto-generated. Do not edit!


(cl:in-package set_pose-msg)


;//! \htmlinclude SetPoseResult.msg.html

(cl:defclass <SetPoseResult> (roslisp-msg-protocol:ros-message)
  ((succeeded
    :reader succeeded
    :initarg :succeeded
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SetPoseResult (<SetPoseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetPoseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetPoseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name set_pose-msg:<SetPoseResult> is deprecated: use set_pose-msg:SetPoseResult instead.")))

(cl:ensure-generic-function 'succeeded-val :lambda-list '(m))
(cl:defmethod succeeded-val ((m <SetPoseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader set_pose-msg:succeeded-val is deprecated.  Use set_pose-msg:succeeded instead.")
  (succeeded m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetPoseResult>) ostream)
  "Serializes a message object of type '<SetPoseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'succeeded) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetPoseResult>) istream)
  "Deserializes a message object of type '<SetPoseResult>"
    (cl:setf (cl:slot-value msg 'succeeded) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetPoseResult>)))
  "Returns string type for a message object of type '<SetPoseResult>"
  "set_pose/SetPoseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetPoseResult)))
  "Returns string type for a message object of type 'SetPoseResult"
  "set_pose/SetPoseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetPoseResult>)))
  "Returns md5sum for a message object of type '<SetPoseResult>"
  "95e696a0d10686913abb262e0b4cbbcf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetPoseResult)))
  "Returns md5sum for a message object of type 'SetPoseResult"
  "95e696a0d10686913abb262e0b4cbbcf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetPoseResult>)))
  "Returns full string definition for message of type '<SetPoseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool succeeded~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetPoseResult)))
  "Returns full string definition for message of type 'SetPoseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool succeeded~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetPoseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetPoseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SetPoseResult
    (cl:cons ':succeeded (succeeded msg))
))
