(cl:defpackage poi_scan-msg
  (:use )
  (:export
   "<POISCANACTION>"
   "POISCANACTION"
   "<POISCANACTIONFEEDBACK>"
   "POISCANACTIONFEEDBACK"
   "<POISCANACTIONGOAL>"
   "POISCANACTIONGOAL"
   "<POISCANACTIONRESULT>"
   "POISCANACTIONRESULT"
   "<POISCANFEEDBACK>"
   "POISCANFEEDBACK"
   "<POISCANGOAL>"
   "POISCANGOAL"
   "<POISCANRESULT>"
   "POISCANRESULT"
  ))

