; Auto-generated. Do not edit!


(cl:in-package poi_scan-msg)


;//! \htmlinclude PoiScanResult.msg.html

(cl:defclass <PoiScanResult> (roslisp-msg-protocol:ros-message)
  ((tasks_completed
    :reader tasks_completed
    :initarg :tasks_completed
    :type cl:integer
    :initform 0))
)

(cl:defclass PoiScanResult (<PoiScanResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PoiScanResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PoiScanResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name poi_scan-msg:<PoiScanResult> is deprecated: use poi_scan-msg:PoiScanResult instead.")))

(cl:ensure-generic-function 'tasks_completed-val :lambda-list '(m))
(cl:defmethod tasks_completed-val ((m <PoiScanResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader poi_scan-msg:tasks_completed-val is deprecated.  Use poi_scan-msg:tasks_completed instead.")
  (tasks_completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PoiScanResult>) ostream)
  "Serializes a message object of type '<PoiScanResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'tasks_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'tasks_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'tasks_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'tasks_completed)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PoiScanResult>) istream)
  "Deserializes a message object of type '<PoiScanResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'tasks_completed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'tasks_completed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'tasks_completed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'tasks_completed)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PoiScanResult>)))
  "Returns string type for a message object of type '<PoiScanResult>"
  "poi_scan/PoiScanResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PoiScanResult)))
  "Returns string type for a message object of type 'PoiScanResult"
  "poi_scan/PoiScanResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PoiScanResult>)))
  "Returns md5sum for a message object of type '<PoiScanResult>"
  "5b91649fc9318ff816a5a104781a31a1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PoiScanResult)))
  "Returns md5sum for a message object of type 'PoiScanResult"
  "5b91649fc9318ff816a5a104781a31a1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PoiScanResult>)))
  "Returns full string definition for message of type '<PoiScanResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 tasks_completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PoiScanResult)))
  "Returns full string definition for message of type 'PoiScanResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 tasks_completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PoiScanResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PoiScanResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PoiScanResult
    (cl:cons ':tasks_completed (tasks_completed msg))
))
